version: '3'
networks:
  internal:
services:
  timescaledb:
    hostname: timescale
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_USER: asset_ms
      POSTGRES_PASSWORD: demo_password
    networks:
      internal:
        aliases:
          - timescale
    expose:
      - 5432
    ports:
      - 55435:5432
  trending-asset-ms:
    image: trending-asset-ms:0.0.0
    environment:
      DB_USER: asset_ms
      DB_PASSWORD: demo_password
      DB_HOST: timescale
      DB_PORT: 5432
      NODE_ENV: production
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      internal:
        aliases:
          - assetms
